input_size: 5
output_size: 2

bit_encoding_type: 'binary' # 'binary' 'gray'
max_neurons: 16
max_weight_value: 10.0
min_weight_value: -10.0
genetic_model: False

genetic_model_precision: 0.1

num_generations: 10
max_fitness_stop_criteria: 500
fitness_saturate_stop_criteria: 100

sol_per_pop: 50

num_parents_mating: 25

parent_selection_type: 'tournament'  # 'tournament','rws','rank','random','sss', 'sus'

keep_parents: 10

k_tournament: 2

keep_elitism: 10
crossover_type: 'uniform' # 'uniform','single_point','two_points','scattered'

crossover_probability: 1
mutation_type: 'random' # 'random','swap','inversion','scramble'

mutation_probability: 0.1
mutation_by_replacement: False

allow_duplicate_genes: True

verbose: 1

time_delay: 0

save_solutions: True
save_best_solutions: True